# Generated by Django 2.0.4 on 2018-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('dresscode', models.CharField(max_length=100)),
                ('event_date', models.DateField(verbose_name='Event date')),
            ],
        ),
    ]
